### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by SajmonOriginal** [SajmonOriginal/solaris#3]
- [x] Implement Wallrunning
- [x] Implement Walljumping
- [x] Fix Climbing
- [x] Add Climbing points
- [x] Add Camera effects, particles, FOV changes, motion blur, crosshair, slowmotion
- [x] Add Basic Enemy
- [x] Pick up gun system
- [x] Implement physics, ragdolls, object pickup
- [x] Gun firing system
- [x] Implement Menu
- [x] Add playable levels
- [x] Add goal object
- [x] Add death and gun drops
- [x] Fix Guns
